acrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('form/', include('main.urls', namespace = 'form')),
    path('landing-page/', include('main.urls', namespace = 'landing-page')),

    
    path('portfolio/', include('folio.urls', namespace = 'folio')),
    path('home/', include('home.urls', namespace = 'home')),
    path('articles/', include('article.urls', namespace = 'article')), # нужен рефакторинг

    path('api/v1/home', include('home.urls'))
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views
from .views import article, by_rubric, article_detail

app_name = 'article'


urlpatterns = [
    path('', article, name='index'),
    path('article/<int:article_id>/', article_detail, name='article_detail'),

    path('rubric/<int:rubric_id>/', by_rubric, name='by_rubric'),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# import readtime 
# Create your models here.

WORDS_PER_MINUTE = 100

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Автор ")
    title = models.CharField(max_length = 50,verbose_name = "Заголовок")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Дата публикации")
    article_image = models.FileField(blank = True,null = True,verbose_name="Загрузка фото")
    slug = models.SlugField(unique=True, max_length=100)
    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Рубрика')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_date']
        verbose_name = "Статья"
        verbose_name_plural = "Статьи" 


class Rubric (models.Model) :
    name = models.CharField (max_length=20, db_index=True, verbose_name='Название')
    
    def __str__(self):
        return self.name
   
    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']

article/views.py
from django.shortcuts import render
from article.models import Article, Rubric
from django.views.generic.detail import DetailView


def article(request):
    model = Article
    article = Article.objects.all()
    rubrics = Rubric.objects.all()
    context = {'articles': article, 'rubrics': rubrics}
    return render(request,'article/index.html',context)



def by_rubric(request,rubric_id):
	ArticleList = Article.objects.filter(rubric = rubric_id)
	rubrics = Rubric.objects.all()
	current_rubric = Rubric.objects.get(pk = rubric_id)
	context = {'articles' : ArticleList,'rubrics' : rubrics,'current_rubric ': current_rubric }
	return render(request,'article/by_rubric.html',context)


def article_detail(request, article_id):
    article = Article.objects.get(id = article_id)
    context = {'article': article}
    return render(request, 'article/article_detail.html', context)

article/templates/article/article-list.html
{% extends 'base.html' %}
{% block content %}
<div class="container mx-auto pt-40 ">
    dsad
    <h1>hello home page</h1>
    <div class="flex">

        <div class="flex flex-col mb-10">
            {% for article in articles %}

            <div class="w-full">
                <!-- Preview Image -->
                {% if article.article_image %}
                <img class="object-cover h-80 mb-10 w-full rounded-lg" src="{{article.article_image.url}}" alt="">
                {% endif %}
            </div>
            <div class="flex flex-col">
                <div class="dark:text-white font-bold text-4/1">{{ article.title }}</div>
                <div> {{article.author.username}}</div>
                <p>{{article.created_date}}</p>
                {{ article.rubric.name }}
                <div class="dark:text-white"> {{article.content|safe|truncatewords:50}}</div>
                <div>Читать далее</div>
                {{post_detail.get_readtime}}
            </div>
            </a>

            {% endfor %}
        </div>


        <div class="bg-red-500 ml-5  p-5 w-3/5 relative">
            <div class="fixed">
                {% for rubric in rubrics %}
                <li>
                    <a href="{% url 'article:by_rubric' rubric.pk %}">{{ rubric.name }}</a>
                </li>
                {% endfor %}
            </div>
        </div>


    </div>

</div>

{% endblock content %}

article/templates/article/article_detail.html
<h1>{{ article.title }}</h1>
<p>{{ article.pk }}</p>

article/templates/article/by_rubric.html
{% extends 'base.html' %}
{% block content %}
<div class="container mx-auto pt-40 ">
   
    <h1>hello home page</h1>
    <div class="flex">
 
    <div class="flex flex-col mb-10">
    {% for article in articles %}
    <a href="{% url 'article:article_detail' article.pk %}">
        <div class="w-full">
            <!-- Preview Image -->
            {% if article.article_image %}
            <img class="object-cover h-80 mb-10 w-full rounded-lg" src="{{article.article_image.url}}" alt="">
            {% endif %}
        </div>
        <div class="flex flex-col">
            <div class="dark:text-white font-bold">{{ article.title }}</div>
            <div> {{article.author.username}}</div>
            <p>{{article.created_date}}</p>
            {{ article.rubric.name }}
            <div class="dark:text-white"> {{article.content|safe|truncatewords:50}}</div>
            <div>Читать далее</div>
            {{post_detail.get_readtime}}
        </div>
    </a>
    {% endfor %}
</div>


<div class="bg-red-500 ml-5  p-5 w-3/5 relative">
    <div class="fixed">
        <a href="{% url 'article:index' %}">Все рубрики</a>
    {% for rubric in rubrics %}
    <li>
        <a href="{% url 'article:by_rubric' rubric.pk %}">{{ rubric.name }}</a>
    </li>
    {% endfor %}
</div>
</div>


</div>

</div>

{% endblock content %}

article/templates/article/index.html
{% extends 'base.html' %}

{% block content %}

{% include 'banner.html' with title='Блог веб-студии Apollo' subtitle="Все, что Вы хотели знать по запуску и масштабированию Ваших бизнес-проектов в интернет." img='https://images.unsplash.com/photo-1529243856184-fd5465488984?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1969&q=80' %}

<div class="">
  <div class="container mx-auto pt-5">
    <div class="flex">
      <div class="flex-col">
        {% for article in articles %}
        <div class="w-full mb-20 hover:shadow-xl transition-all  bg-white dark:bg-darkLight border border-white mb-5 dark:border-opacity-10 ">

          <div class="relative">
            {% if article.article_image %}
            <img  class="h-96 w-full object-cover" src='{{article.article_image.url}}' alt="">
            {% endif %}
            <div class="absolute bottom-5 left-5 z-50 text-white bg-secondary p-2">{{ article.rubric.name }}</div>
          </div>
          <div class="p-5">
            <div class="flex pt-5">
              <span>Автор: {{article.author.username}}</span><span class="mx-5">|</span>
              <span>{{article.created_date}}</span>
            </div>
            <a class="pt-10" href="{% url 'article:article_detail' article.pk %}">
              <h1 class="font-bold pb-5 pt-3 text-2xl">{{ article.title }}
            </a>
            </h1>
            {{article.content|safe|truncatewords:40}}

          </div>


        </div>
        {% endfor %}
      </div>
      <div class="w-7/12 ml-5 ">
        <div class="bg-white dark:bg-darkLight border border-white mb-5 dark:border-opacity-10 p-5">
          <div class="py-5">
            <div class="flex">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-3 text-darkGray" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
              </svg>
              <span class="uppercase">Рубрики</span>
            </div>
          </div>
          {% for rubric in rubrics %}
          <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3 mr-3 text-darkGray" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
            <div class="py-3"><a href="{% url 'article:by_rubric' rubric.pk %}">{{ rubric.name }}</a></div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}