acrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('form/', include('main.urls', namespace = 'form')),
    path('landing-page/', include('main.urls', namespace = 'landing-page')),

    
    path('portfolio/', include('folio.urls', namespace = 'folio')),
    path('home/', include('home.urls', namespace = 'home')),
    path('articles/', include('article.urls', namespace = 'article')), # нужен рефакторинг

    path('api/v1/home', include('home.urls'))
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'


urlpatterns = [
path('', views.index, name='index'),
path('form', views.form, name='form'),
path('landing-page', views.landing, name='landing-page'),
path('thanks', views.thanksForm, name='thanks'),
]

templates/banner.html
<div style="background-image: url({{ img }}); height:{{ h }}" class="bg-primary h-96 text-4xl text-white flex flex-col items-center justify-center relative">
   <h1 class="home__title lg:text-8xl text-3x1 mb-5 lowercase">{{ title }}</h1> 
   <h2>{{ subtitle }}</h2>


   
   <div
   class="absolute bottom-10 z-50 border-t border-white absolute border-opacity-25 w-full flex items-center flex-col justify-center">
   <div
       class="p-5 transform rotate-45 border border-white border-opacity-25 relative -top-5 bg-primary flex items-center justify-center">
       <div class="transform -rotate-45 absolute z-50">
           <svg @click="$scroll('#about')" xmlns="http://www.w3.org/2000/svg"
               class="h-4 w-4 text-white  cursor-pointer  animate-bounce" fill="none" viewBox="0 0 24 24"
               stroke="currentColor">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                   d="M19 14l-7 7m0 0l-7-7m7 7V3" />
           </svg>
       </div>
   </div>
</div>
   
</div>

templates/base-article.html
{% extends 'base.html' %}
{% block content %}




{% endblock content %}

templates/base-thx.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "css/style.min.css" %}'>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    {% block styles %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Jura&display=swap" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpine-collective/alpine-magic-helpers@1.2.x/dist/scroll.min.js" defer></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}" defer></script>
    
    

    <title>😎Apollo.kz - создание сайтов</title>


    <script>
        var myNav = document.getElementById("nav");

        window.onscroll = function () {
            "use strict";
            if (document.body.scrollTop >= 280 || document.documentElement.scrollTop >= 280) {
                myNav.classList.add("scroll");
            } else {
                myNav.classList.remove("scroll");
            }
        };
    </script>



</head>

<body x-data="{ 'isDialogOpen': false, 'darkMode': false }" @keydown.escape="isDialogOpen = false" x-init="
darkMode = JSON.parse(localStorage.getItem('darkMode'));
$watch('darkMode', value => localStorage.setItem('darkMode', JSON.stringify(value)))">
    <div :class="{'dark': darkMode === true}">
        <div class="bg-gray dark:bg-primary dark:text-white text-black">
            {% include 'navbar-thx.html' %}
            {% include 'modal.html' %}
            {% block content %}
            {% endblock content %}
            
        </div>
    </div>
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "css/style.min.css" %}'>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    {% block styles %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;900&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/alpine-collective/alpine-magic-helpers@1.2.x/dist/scroll.min.js"
        defer></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}" defer></script>
    <meta name="title" content="Создание сайтов Астана (Нурсултан) Apollo.kz">
    <meta name="description"
        content="Создание сайтов в Астане - Apollo.kz. Заказать создание сайта Астана. ☎ +7 7761604911. Разработка сайтов Астана (Нур-Султан). Сайты под ключ">
        <meta name="mailru-domain" content="SpM0GUjJRUsbPqR2" />
    <title>😎Apollo.kz - создание сайтов в Астане</title>


    <script>
        var myNav = document.getElementById("nav");

        window.onscroll = function () {
            "use strict";
            if (document.body.scrollTop >= 280 || document.documentElement.scrollTop >= 280) {
                myNav.classList.add("scroll");
            } else {
                myNav.classList.remove("scroll");
            }
        };
    </script>



    <!-- <div
        class="fixed bottom-10 right-10 bg-white w-20 h-20 z-60 rounded-full animate-pulse flex items-center justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="green" width="80" height="80" viewBox="0 0 24 24">
            <path
                d="M12.031 6.172c-3.181 0-5.767 2.586-5.768 5.766-.001 1.298.38 2.27 1.019 3.287l-.582 2.128 2.182-.573c.978.58 1.911.928 3.145.929 3.178 0 5.767-2.587 5.768-5.766.001-3.187-2.575-5.77-5.764-5.771zm3.392 8.244c-.144.405-.837.774-1.17.824-.299.045-.677.063-1.092-.069-.252-.08-.575-.187-.988-.365-1.739-.751-2.874-2.502-2.961-2.617-.087-.116-.708-.94-.708-1.793s.448-1.273.607-1.446c.159-.173.346-.217.462-.217l.332.006c.106.005.249-.04.39.298.144.347.491 1.2.534 1.287.043.087.072.188.014.304-.058.116-.087.188-.173.289l-.26.304c-.087.086-.177.18-.076.354.101.174.449.741.964 1.201.662.591 1.221.774 1.394.86s.274.072.376-.043c.101-.116.433-.506.549-.68.116-.173.231-.145.39-.087s1.011.477 1.184.564.289.13.332.202c.045.072.045.419-.1.824zm-3.423-14.416c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm.029 18.88c-1.161 0-2.305-.292-3.318-.844l-3.677.964.984-3.595c-.607-1.052-.927-2.246-.926-3.468.001-3.825 3.113-6.937 6.937-6.937 1.856.001 3.598.723 4.907 2.034 1.31 1.311 2.031 3.054 2.03 4.908-.001 3.825-3.113 6.938-6.937 6.938z" />
        </svg>
    </div> -->

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date(); k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(85965704, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true,
            webvisor: true
        });
    </script>

    <noscript>
        <div><img src="https://mc.yandex.ru/watch/85965704" style="position:absolute; left:-9999px;" alt="" /></div>
    </noscript>
    <!-- /Yandex.Metrika counter -->


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-41VR65JJRD"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-41VR65JJRD');
    </script>


    <meta name="google-site-verification" content="h6GsWYhCsifdgVVpZWBM5-4z2GB9UMmTIyJPNwLMWzY" />

</head>

<body class="bg-gray flex flex-col h-full" x-data="{ 'isDialogOpen': false, 'darkMode': false }"
    @keydown.escape="isDialogOpen = false">

    <div style=" flex: 1 0 auto;">


        {% include 'navbar.html' %}



        {% include 'modal.html' %}
        {% block content %}
        {% endblock content %}



    </div>

    {% include 'footer.html' %}

</body>

</html>

templates/footer.html
{% load static %}






<footer id="contact" class="bg-primary h-full  bg-marketing">



  <!-- <section id="contact" class="py-20 text-black bg-red  ">

    <div class="overflow-hidden">
        <div class="background absolute w-full top-0 left-0 z-50">
            <div class="star1 star"></div>
            <div class="star2 star"></div>
            <div class="star3 star"></div>
            <div class="star4 star"></div>
        </div>
        <div class="container mx-auto relative z-50 text-white">
  
  
       
  
  
        </div>
    </div>
  </section> -->

  <div class="relative lg:h-full h-screen g:mx-0 mx-5">

    <div class="flex flex-col h-80 w-full">


      <div class="flex flex-col items-center w-full pb-10  z-50 absolute -top-20 ">




        <div class="container relative ">
          <div
            class="lg:py-5 lg:px-10 p-5 bg-opacity-90 bg-help bg-secondary text-white w-full rounded-lg flex lg:flex-row flex-col items-center justify-between relative">

            <div class="lg:py-10 py-5  flex flex-col lg:items-start items-center">

              <div class="flex  lg:flex-row flex-col items-center relative z-50">
                <div class="div">
                  <div
                    class="w-20 h-20 lg:mb-0 mb-10 p-1 bg-white text-primary rounded-full shadow-xl flex items-center justify-center">
                    <span class="text-4xl">
                      <img class="w-10 h-10" src="{% static '/img/icons/frame/5.svg' %}" alt="">
                    </span>
                  </div>
                </div>

                <div class="pl-5 w-full flex flex-col justify-center items-start">
                  <h1 class="lg:text-4xl text-4xl lg:pb-2 pb-5  lg:text-3x1 font-bold text-lg text-white">
                    Узнать цену за 30 минут</h1>

                  <div class="flex w-full lg:flex-row flex-col items-start w-full">

                    <span class="lg:pr-5 py-1  mr-5">
                      Ответим через: 5 минут
                    </span>



                    <span class="lg:px-5 py-1 lg:mr-5">
                      Сделаем индивидуальный просчет сайта
                    </span>


                  





           


                  </div>
                </div>
              </div>

            </div>

            <div class="relative lg:my-0 my-5 z-50">
              <a href="https://wa.me/+77761604911" class="border
              bg-white
              w-full
              text-center
              text-secondary
               border-primary
               border-opacity-20
               focus:outline-none
               py-4 px-6 rounded-lg
               uppercase
               text-sm
               tracking-wide
               font-bold
            
               hover:border-none
               cursor-pointer
               transition flex
               items-center ">
                Написать в whatsapp
              </a>
            </div>


          </div>
        </div>

        <!-- 
        <div class="container w-full lg:mx-0 mx-5 ">

          

          <div class="p-5 bg-white relative w-full flex-col rounded-lg flex items-center ">


            <div class="absolute -top-11 w-20 h-20 text-primary p-1 bg-white dark:bg-blueLight rounded-full shadow-xl flex items-center justify-center">
              <span class="text-4xl">
                <img class="w-10 h-10" src="{% static '/img/icons/frame/5.svg' %}" alt="">
              </span>
          </div>

            <div class="pt-10 text-center flex flex-col items-center ">

              <h1 class="lg:text-4xl mb-10  text-3x1 home__sub-title">Узнать цену за 30 минут</h1>
          
               <p class="py-2 mb-5 lg:text-lg text-sm">По нашему опыту, большинство клиентов не знают, какой нужно выбрать им сайт.<br>
                Наш специалист готов ответить на инетерсующие вас вопросы и подсказать какой сайт нужен вам.
              </p> -->


      </div>


    </div>







  </div>


  </div>



  <div
    class="border-t border-white border-opacity-20 absolute bottom-0 z-50 flex w-full lg:flex-row flex-col w-full items-end lg:justify-between p-5 ">
    <div class="lg:w-1/3 w-full flex lg:justify-start justify-center lg:order-none order-2">
      <span class="uppercase text-sm tracking-widest text-white ">ТОО "Apollo Company" 2021</span>
    </div>
    
    <div class="lg:w-1/3 w-full flex lg:justify-end justify-center">
      <span class="uppercase text-sm tracking-widest text-white lg:py-0 py-3">Все права защищены</span>
    </div>
  </div>


  </div>
  </div>

</footer>

templates/modal.html
<div x-cloak class="overflow-auto" style="background-color: rgba(0,0,0,0.5)" x-show="isDialogOpen"
    :class="{ 'fixed inset-0 z-60 flex items-center justify-center': isDialogOpen }">

    <div class="bg-white shadow-2xl m-4 sm:m-8 text-black" x-show="isDialogOpen" @click.away="isDialogOpen = false">
        <div class="flex justify-between items-center border-b border-primary border-opacity-20 p-2 text-xl">
            <h6 class="text-xl font-bold">Условия акции</h6>
            <button type="button" @click="isDialogOpen = false">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
            </button>
        </div>
        <div class="p-5">
            <p class="mb-5">
                <h3 class="font-bold pb-5"> Условия акции</h3>
                В настоящее время, наша компания предоставляет акцию только клиентам,</br> которые заказали услугу от
                100
                000 (сто тысяч) тенге.
               <h3 class="font-bold py-5"> Компания в праве отказать в акции, если:</h3>
            <ul>
                <li>Если срок действия акции истек на данный момент;</li>
                <li>Заказчик не продоставил в обговоренный срок информацию;</li>
                <li>Заказчик представлил контент неподобающего содержания;</li>
            </ul>

            </p>

        </div>
    </div>
</div>

templates/navbar-thx.html
{% load static %}
<div
    class="flex text-black w-full justify-center lg:px-0 z-60  mx-auto delay-100 transition-colors duration-300 ease-in-out ">




    <div class="lg:px-10 flex w-full items-center text-white fixed z-60 dark:bg-primary text-black shadow-md border-b border-white border-opacity-25"
        x-data="{ atTop: true }" :class="{ 'bg-primary bg-opacity-90 ' : !atTop }"
        @scroll.window="atTop = (window.pageYOffset > 40) ? false : true">
        <div class="navbar w-full flex justify-center dark:text-white">
            <nav class="flex items-center lg:px-0 px-2 justify-between relative z-40 flex-wrap py-6 fixed w-full top-0"
                x-data="{ isOpen: false }" @keydown.escape="isOpen = false"
                :class="{ 'shadow-lg bg-transparent' : isOpen }">

                <!--Logo etc-->
                <div class="pl-5 flex items-center flex-shrink-0 text-white mr-6">
                    <a class="logo" href="{% url 'main:index' %}">
                        Apollo
                    </a>
                </div>

                <div class="hidden lg:block">
                    <span class="pr-5 uppercase font-bold">Остались вопросы?</span>
                    <a href="tel:87781647391">8 778 164-73-91</a>
                </div>


                <div class="lg:hidden block font-bold ">


                    <a href="tel:87781647391">8 778 164-73-91</a>

                </div>

            </nav>

        </div>


    </div>

templates/navbar.html
{% load static %}
<div
    class="flex text-black w-full justify-center lg:px-0 z-60  mx-auto delay-100 transition-colors duration-300 ease-in-out ">




    <div class="lg:px-10 flex w-full items-center text-white fixed z-60 dark:bg-primary text-black shadow-md border-b border-white border-opacity-25"
        x-data="{ atTop: true }" :class="{ 'bg-primary bg-opacity-90 ' : !atTop }"
        @scroll.window="atTop = (window.pageYOffset > 40) ? false : true">
        <div class="navbar w-full flex justify-center dark:text-white">
            <nav class="flex items-center lg:px-0 px-2 justify-between relative z-40 flex-wrap lg:py-6 py-3 fixed w-full top-0"
                x-data="{ isOpen: false }" @keydown.escape="isOpen = false"
                :class="{ 'shadow-lg bg-transparent' : isOpen }">

                <!--Logo etc-->
                <div class="pl-5 flex items-center flex-shrink-0 text-white mr-6">
                    <a class="logo" href="{% url 'main:index' %}">
                        Apollo
                    </a>
                </div>

                <div class="lg:hidden block font-bold ">


                    <a href="tel:87781647391">8 778 164 73 91</a>

                </div>

                <!--Toggle button (hidden on large screens)-->
                <button @click="isOpen = !isOpen" type="button"
                    class="block lg:hidden p-2 text-white hover:text-white focus:outline-none focus:text-white"
                    :class="{ 'transition transform-180': isOpen }">
                    <svg class="h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path x-show="isOpen" fill-rule="evenodd" clip-rule="evenodd"
                            d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0 1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828 4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z" />
                        <path x-show="!isOpen" fill-rule="evenodd"
                            d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z" />
                    </svg>
                </button>


                <!--Menu-->
                <div class="w-full lg:px-0 px-5 flex-grow lg:flex lg:items-center lg:w-auto lg:relative absolute lg:top-0 top-20 left-0 z-50"
                    :class="{ 'block shadow-3xl': isOpen, 'hidden': !isOpen, 'bg-primary' : isOpen }"
                    @click.away="isOpen = false" x-show.transition="true">
                    <ul class="pt-6 lg:pt-0 list-reset lg:flex items-center uppercase text-sm font-bold">
                        <li class="mr-3">
                            <a href="{% url 'main:index' %}"
                                class="cursor-pointer inline-block py-2 px-2  no-underline">
                               Главная</a>
                            </a>
                        </li>
                        <li class="mr-3">
                            <a class="cursor-pointer inline-block  no-underline hover:text-gray-200 hover:text-underline py-2 px-2"
                                @click="$scroll('#about'), isOpen = false">
                                О нас
                            </a>
                        </li>

                        <li class="mr-3">
                            <a class="cursor-pointer inline-block  no-underline hover:text-gray-200 hover:text-underline py-2 px-2"
                                @click="$scroll('#folio'), isOpen = false">
                                Наши работы
                            </a>
                        </li>

                        <!-- <li class="mr-3">
                            <a class="cursor-pointer animate-pulse inline-block  no-underline hover:text-gray-200 hover:text-underline py-2 px-2"
                                @click="$scroll('#sale'), isOpen = false">
                                Акция недели
                            </a>
                        </li> -->

                        <!-- <li class="mr-3">
                            <a class="cursor-pointer inline-block  no-underline hover:text-gray-200 hover:text-underline py-2 px-2"
                                @click="$scroll('#product'), isOpen = false">Продукты
                            </a>
                        </li> -->

                        <!-- <li class="mr-3">
                            <a href="{% url 'article:index' %}"
                                class="cursor-pointer inline-block  no-underline hover:text-gray-200 hover:text-underline py-2 px-2">Статьи
                            </a>
                        </li> -->


                        <!-- <li class="mr-3">
                <a class="inline-block text-white no-underline hover:text-gray-200 hover:text-underline py-2 px-2"
                    href="#" @click="$scroll('#second'), isOpen = false">отзывы
                </a>
            </li> -->


                        <li class="mr-3 lg:mb-0 mb-5">
                            <a class="cursor-pointer inline-block  no-underline hover:text-gray-200 hover:text-underline py-2 px-2"
                                @click="$scroll('#contact'), isOpen = false">Контакты
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>
        </div>




        <div class="navbar__right justify-end w-full items-center relative z-50 lg:flex hidden ">
            <div class="pr-5 font-bold flex">
                <div class="flex items-center mr-5">
          
                </div>
                <div class="flex items-center dark:text-white">


                    <a href="tel:87781647391">8 778 164-73-91</a>

                </div>
            </div>
            <a href="form"
                class="bg-secondary hover:bg-secondaryLight transition-all px-5 uppercase text-xs font-bold tracking-widest py-3 rounded-lg">Заказать
                звонок</a>

            
        </div>

    </div>


</div>